#ENC[AES256_GCM,data:XQklDmJdTWwS0dJPbdxarXUVSiE29elCF+Q/yH5fxVhksIcXOoLXhAs=,iv:vMXVkMdzPdwmh578R8K2rYNHBSmK+ThWg0UIRlcD14A=,tag:1rfF2YjTWGeaSbXadzTIvg==,type:comment]
ssh_key_path: ENC[AES256_GCM,data:EvQyF+Jc4Vb8Vg05/o9u+Y3HNmmIZe8EbGF2t9Sz7ADupZ4+icE=,iv:QqbY4zRfWm80hPKq2dil8OVPN7/rOhv8hwFa5CAdLtc=,tag:u7D+BX+WUYaj3o+s9XgNow==,type:str]
target_ssh_port: ENC[AES256_GCM,data:+AA6dEY=,iv:B6TlEqxkDlSOUfU8LSsaFY64JcSwiYxR9NH+32bthkY=,tag:kQtahFC+wSvnwgwZ1zKAPw==,type:int]
nginx_hosts:
    dev:
        ip: ENC[AES256_GCM,data:RoQTMLwpIHPj0Q1L3Ik=,iv:0kDZjyPiIECjsvrsMUM/Y/jesRtvc4Sv2aChAFgjcYM=,tag:h0z/NCqEFyKqFWsDoLnthw==,type:str]
        k8s_nodes:
            - ENC[AES256_GCM,data:ei7DlJbVFM7Zuw==,iv:MlH+r8qGPsYMMCszR92xs30DUvtYwpMFKYcDsDDObCU=,tag:Ze2CmUZksCaAYQv7saPmpQ==,type:str]
            - ENC[AES256_GCM,data:ofQHhpQCulQoxg==,iv:6vY5Ns8PSUDEPILLrvO+HrgPQ8pjUGfUuU+u7aYo3W4=,tag:cK2ZrYmM6TpHgA+jaPLUPg==,type:str]
    prod:
        ip: ENC[AES256_GCM,data:7/p7iFmOJoMowFzU4Q==,iv:Rgx/cUbgAE0N7untEBHoOUJdCeaeJRkcYZYgzct/lvQ=,tag:YmHin9ThXwkJeJNpjM4AJQ==,type:str]
        k8s_nodes:
            - ENC[AES256_GCM,data:RvvfDyADSD1Z,iv:I9RCqvrZNKZR/HXry93OpxQUF+A0B4nL+hcbU5z8w54=,tag:UweBh3uDdbLlfacpDIFhsw==,type:str]
            - ENC[AES256_GCM,data:noMg2fcTa/7zpQ==,iv:IpqRw378yNn/V1rfNG7IHJp1+lp74y4euV6+gIBCcD8=,tag:5NJ4idR6gTzsWPIAIS2pJQ==,type:str]
            - ENC[AES256_GCM,data:5IiHKG4Rwz0=,iv:mpFuKvPgKgqI8RMKiIBvjNzTMkeoJLswnYNDVEyD/nI=,tag:SO5UqyhEQEd+Dh/Y4bTU5g==,type:str]
            - ENC[AES256_GCM,data:Dkz0EZKvYggeGA==,iv:M722g11kKXi/FTrDE8oNi8o1VDVg0BMX3SX28Ifni44=,tag:3GI25m5/RU3srxfEvfD3qg==,type:str]
admin_email: ENC[AES256_GCM,data:7C/lXJ/wr9i4hvrYKDQ6iiOClse3OpEWlTE=,iv:+7IN3UHhy5RYE4GMhfbjbWXQL/rsDFNHR1RuNKgkDMo=,tag:dR2odpg4fuvNmqEqBvSMjw==,type:str]
#ENC[AES256_GCM,data:xbiPgblSE4cdqjQcxCiIHx1H,iv:UXmSKe6u5pg84IBNZ3x/9oARmIZ9DQWlzDPpsYzWUUA=,tag:SofYcRm3ia+ZguOJlgWIfQ==,type:comment]
argocd_kubeconfig:
    dev: ENC[AES256_GCM,data:mHtGz+3Xfibc+AOVrgCr2o2d04hnknvMamBTzX4Oz1g=,iv:+8eUhEgRZ7UhppS4na4XuHMTV6QqE+6mJo61sWeRhv0=,tag:BggQTjj83Cr2doYBz3cq0g==,type:str]
    prod: ENC[AES256_GCM,data:Fj5nUNiIq6cBLQCFe+ICIHi5C7RFrlXzYCzA3ZEsYj8u,iv:shokcCY/W/VIb/axFA6iP64OIFu0aQMBnnixPrWJOmo=,tag:r709W2w192bjdzESsYU++Q==,type:str]
gitops_repo_path: ENC[AES256_GCM,data:KttStyJ99Ceu5RyzQsHnw8WLUg9Ifnus3ZcVwRUgj0MGh0VcV4uGEmVgKZdkrdj05Uw=,iv:QA+tlfrTnliyRPALZyNZcla2opb6Z76c5HE1nPZZQ7o=,tag:2mJ+V5uWCrPFwJXay1JjjQ==,type:str]
#ENC[AES256_GCM,data:UL12VdaeOvOYWzw=,iv:1ZWAYRchKpe4Ct1RvnhfDIh8hl3vNMAP7yHCimrBvMU=,tag:HYOyEcbAPwvQuc/7kSJ0NQ==,type:comment]
nfs_hosts:
    dev:
        ip: ENC[AES256_GCM,data:BqZ3fnjo3V4SPA==,iv:oMoE1tC+6QcCAjr1h3Qk4jpuNz0Ao9Ei/J7sG5DHdQI=,tag:9sWlP8jNRRQ9U8ySU6XwzQ==,type:str]
        network: ENC[AES256_GCM,data:Gzf+simLr3Mh6do=,iv:bEtVsuHyDrQc7w+v9TMR4mTn5N/cdPqEmmTPUcQWY48=,tag:NTjoiCXH1ddyRFblcF7xkQ==,type:str]
    prod:
        ip: ENC[AES256_GCM,data:PYLTjzCGXfRm0w==,iv:HVdTUMxwOUEP8jJwuTTvIICBN81GAYgARLdzQKkZ0ts=,tag:t4Zi0/z3QcEeXQX1VivYuQ==,type:str]
        network: ENC[AES256_GCM,data:keyc8anSWvOtFWY=,iv:/kKn6I8Vt6y/lhtwgaJHI3xAGRZ32N5kAJLtznNoRYc=,tag:h2rJlp9j8abkkEDWNjl/Jg==,type:str]
freeipa_hosts:
    dev:
        ip: ENC[AES256_GCM,data:R9AW57RHtdxt,iv:TJbuc08DfUL21W5h1FtWM52MDcRzGLR90ziApwZ4q1w=,tag:GH0KaREYcEgRdMEKzVxjeQ==,type:str]
    prod:
        ip: ENC[AES256_GCM,data:ucXr415OmeEbDQ==,iv:UOB9LkMZdWl9ewPxkuDDyATPXf5S1DBfOlkPtun7v7E=,tag:eDMqbDJ8Cyb2dl5jNxiA9g==,type:str]
#ENC[AES256_GCM,data:MWU0SXr2XgmmZP1e7jeP4w==,iv:C0FHE72ENST6b0Bv1qOkprz+K7Ueb5aDac9yo5/KWTo=,tag:jd3z+RSBRcupEoIWZYBjYA==,type:comment]
freeipa_admin_password:
    dev: ENC[AES256_GCM,data:mkcie5QxDKQglPcCaUhkdt+qo1Yjjg0iKkiTVAxCbNNsDOANG3w98Mkd,iv:dhps3H3ZqqaPsODOJCn+vHiJCBe+pb6wH+8tSExQyT0=,tag:bqgTs7ikSXT0sesNX2tV0Q==,type:str]
    prod: ENC[AES256_GCM,data:zbkNLbXRvbNbX/pXyBjI7D4XCLrSBtFOIg5NjcxPGVKid1k6yNruYj9xOw==,iv:o+sUBoRTGE0qhLdsYPzJY/0m43OJQ7+0SN4pUEvQsZQ=,tag:gl+zqr/BOYRasJmog5/n0g==,type:str]
freeipa_ds_password:
    dev: ENC[AES256_GCM,data:hHK8mJZD4kD0vBactMTFa15JVU0hs/Q5ZavGBKY85gYOOX5D2fwqQERj,iv:gpksp7DREiggG7AdaoTJJZa2SY7gIicHr6AL5oGAmGw=,tag:MfRw283EFUQYXKAHeQ08dQ==,type:str]
    prod: ENC[AES256_GCM,data:r7y3TJP8N2Kpe+wmwT/zDBvW4HC2uEOGsBLW+p+jfkMl8VLy3exIdpg42Q==,iv:bXouKOf15YF/RQkCjaxxTFWptmnEPjdThxMK5j8dgJk=,tag:n4ug3jkkO594aKBm3IG7Xw==,type:str]
#ENC[AES256_GCM,data:yKXDeljQ08fP0ttYwLA=,iv:/fFDedhFXw7G/4CZgrbsENnc1D4eB8ebbwl3adiMwlk=,tag:DqNP/4SBzUeESl2lAXII+A==,type:comment]
guacamole_target_ssh_port: ENC[AES256_GCM,data:z1l4cdE=,iv:MabA04FsOxuZGzfc+yAfhlatc5nGQTra0AKvqphWb5Y=,tag:oHE46EjKZPrsBweecGa57Q==,type:int]
guacamole_hosts:
    dev:
        workspacetest:
            ip: ENC[AES256_GCM,data:OPmhYhFNACqe,iv:N8hcUG5LIiqdUXSHFqO6ZDtSTEn9Tlg5I0QY6ArFPRU=,tag:y2UgojlMIv/5xUKx2uP5Qg==,type:str]
    prod:
        indoctestproject:
            ip: ENC[AES256_GCM,data:rMn8uQTHIa/syw==,iv:WPEA+SVhAJPT/TNQnCdEXpmmoYeJHpZ/5PpoOg+7hYE=,tag:kjaDNZOxkbvMxmi9sspD7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jqmtl54n9w063hu5s5nw208ds440u696m693pp63x4f78rxdevkskpxqnh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MW9IM0dicnZNS3RhcDU2
            RHBDQWVaaTNFMnpCdGFNZXVsdlhiaDRhK2pvCkEyWE44a0ZHckFVejNsbGNFTy9U
            MUZUTU5Xdk94c0dqWndqVENEaERNTXcKLS0tIHkrRGFLMGpkWThJOGN3dXFDSkt5
            dE4vTDZIbmRwaUJUU1hxWmNhOWRKSjgKPauvWCMSAG/QRmWRDowXAMol2QJePglG
            upHfNr34aGVUqMXgqgYWePfuaGusJOk5HnGutl5Dn1iGfy116/cr+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ywpmeqt0x68hapd7pzk5sj0k57hfhkzra77jvxdnd7y5gmnppf2qzpe3ph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcm9JY0ZuMmZQSVk2UHk2
            QXRxS0VTQzJsL056eHEySlYyR21LaDkwd0hBCi90b3BHN0I5ck42cFN2RndyV2VJ
            cEYwN0xiRDJFcFQxb3JpM2NwdzlEeG8KLS0tIDRZczB0WTBIcnpZRjJFL1k2RnJZ
            aTljT0s0VEFpc1JVY0NiZzRCRklnUk0KcuRmoBcd9kob2oHEOBhQ7ClRBc3TbYxm
            F3pMWD/oHftIj/DibUbC0rb/VHRVHEZ1WmMMWBcQbWjY41zklCCysQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n3pwsxtr95zy6l5qlxums45nuc5xp2uvu3jh4ez03y4mcy3cn4wsygrla4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNc0pCTDlUV1RuN3VDRUdn
            Sm90c3ZvWHc5RE9ZUzFYL2huOG5INXlETVFRCkk2eWdPMUhhWEhPTHNCQ21HczNU
            S3RmSnRwek9ER0FlVHFXRVJUSlFOeDQKLS0tIFN6ZG83SGcrTjBEMkI3ekhlZ3lz
            Qm8wUHFValVVaElHdHNMd2h3aDJzSmsKq171USAVJ2oAJK1qSQS4v6kZI1pfq7J1
            XMlaFfC+FQqcaCBSp+S3OV1NyNR9SHqUwQRR60PrZ9NsHQVdTs5jaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T09:06:08Z"
    mac: ENC[AES256_GCM,data:uUwuPP10HUeRuSNpOUTMXDSjGE3aNC4IRxphztB8tVc/xp8M0KwDe5x8A0ewcrAkuqm/udUNtH9Pxj9sKXG5oKzXCkdI7Qmw3W7Yn/WRx1ltuuCbFGBKk/ud1TWyZNobE0MChYQVb0YeTXeMbaWz83HycIh/shB9clcVew0iw1c=,iv:EfKjUprSIVB5fJpkyP8BZS9vggE1WsOU6wPM6gcmfdQ=,tag:4WzJmaiyoMoQOhVG6mXGdQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
